# Generated by Django 2.2 on 2021-06-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
