# Generated by Django 2.2 on 2021-06-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official',
            old_name='office',
            new_name='elected_office',
        ),
        migrations.RemoveField(
            model_name='official',
            name='indice',
        ),
    ]
