# Generated by Django 2.2 on 2021-06-13 15:49

from django.db import migrations, models
import rateApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0002_profile_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=rateApp.models.filepath),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
