# Generated by Django 2.2 on 2021-06-16 01:37

from django.db import migrations, models
import rateApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0003_auto_20210615_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=rateApp.models.filepath),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=rateApp.models.filepath),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=rateApp.models.filepath),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_likes',
            field=models.ManyToManyField(related_name='comment_likes', to='rateApp.User'),
        ),
    ]
