# Generated by Django 2.2 on 2021-06-16 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0004_auto_20210616_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
