# Generated by Django 2.2 on 2021-06-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0005_remove_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
