from django.urls import path
from . import views

urlpatterns = [
#     path('', views.profile),
#     path('signup/', views.signup, name ='signup'),
#     path('signin/', views.signin, name = 'login'),
#     path('signout/', views.signout, name = 'logout'),
#     path('deleteAcc/', views.delete),
#     path('delete/<username>', views.delete_user),
    path('', views.index),
    path('login/', views.login),
    path('register/', views.register),
    path('success/', views.success),
    path('daily/', views.daily),
    path('view_officials', views.view_officials),
    path('show_officials/', views.show_officials),
    path('officials/', views.show_officials),
    path('rate_official/<str:name>/<str:elected_office>', views.rate_official),
    path('addRate/<str:name>/<str:elected_office>', views.addRate),
    path('rate/<str:name>/<str:elected_office>', views.rate_official),
    path('logout', views.logout),
    path('addReply/<str:name>/<str:elected_office>', views.addReply),
    path('addOpinion/<str:name>/<str:elected_office>', views.addOpinion),
    path('deleteReply/<int:reply_id>', views.deleteReply),
    path('deleteOpinion/<int:opinion_id>', views.deleteOpinion),
    # path('delete_user/<int:user_id>', views.delete_user),
    path('message', views.message),
    path('comment', views.comment),
    path('deleteMessage/<int:message_id>', views.deleteMessage),
    path('deleteComment/<int:comment_id>', views.deleteComment),
    path('zipcode/', views.zipcode),
    path('upload/', views.image_upload_view),
    path('editMessage/<int:message_id>', views.editMessage),
    path('updateMessage/<int:message_id>', views.updateMessage),
    path('editComment/<int:comment_id>', views.editComment),
    path('updateComment/<int:comment_id>', views.updateComment),
    path('delUser/<int:user_id>', views.delUser),
    path('editUser/<int:user_id>', views.editUser),
]